services:
  - type: web
    name: enurwa-epic-safaris
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn enurwa_safaris.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        value: "generateValue: true"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: enurwa_db
          property: connectionString 