# Generated by Django 5.0.3 on 2025-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accommodation_preference',
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_package_type',
            field=models.CharField(choices=[('standard', 'Standard Package'), ('premium', 'Premium Package'), ('luxury', 'Luxury Package')], default='standard', max_length=20),
            preserve_default=False,
        ),
    ]
