# Generated by Django 5.0.3 on 2025-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='climate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_airport',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='wildlife_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
