# Generated by Django 5.0.3 on 2025-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_group_size',
            field=models.PositiveIntegerField(default=6, help_text='Maximum number of people allowed in a group'),
        ),
    ]
