# Generated by Django 5.0.3 on 2025-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per person in USD', max_digits=10),
        ),
    ]
